In [ ]:
import pandas as pd

data = {
    'Nome': ['Ana', 'Joao', 'Maria'],
    'Idade': [25, 30, 28],
    'Salário': [5000, 7000, 6000]
}

df = pd.DataFrame(data)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr+10)
print(arr-1)
print(arr*2)
print(arr**2)
print(arr//2) #divisão inteira (Arredonda para baixo)

[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[0 1 1 2 2]


In [ ]:
import pandas as pd
import numpy as pd

np.random.seed()
meses = np.array(['Jan', 'Fev', 'Mar', 'Abr', 'Mai'])
vendas = np.random.randint (100, 500, size=5)
custos = vendas * np.random.uniform (0.3, 0.7, size=5)

print(meses)
print(vendas)
print(custos)

['Jan' 'Fev' 'Mar' 'Abr' 'Mai']
[323 172 216 144 358]
[225.1846035   93.52775141 144.83802238  78.92482269 120.01366376]


In [ ]:
import pandas as pd
import numpy as np

dados = pd.DataFrame({
    'Mês': meses,
    'Vendas (R$)': vendas,
    'Custos (R$)': custos,
    'Clientes': np.random.poisson(lam=50, size=5)
})

display(dados)

Mês  Vendas (R$)  Custos (R$)  Clientes
0  Jan          323   225.184604        51
1  Fev          172    93.527751        65
2  Mar          216   144.838022        40
3  Abr          144    78.924823        42
4  Mai          358   120.013664        51

In [ ]:
dados['Lucro (R$)'] = dados['Vendas (R$)'] - dados['Custos (R$)']

display(dados)

Mês  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)
0  Jan          323   225.184604        51   97.815396
1  Fev          172    93.527751        65   78.472249
2  Mar          216   144.838022        40   71.161978
3  Abr          144    78.924823        42   65.075177
4  Mai          358   120.013664        51  237.986336

In [ ]:
dados = dados.drop(columns=['Teste'])

In [ ]:
dados['Teste'] = (dados['Vendas (R$)'] * dados['Custos (R$)']).round(2)

display(dados)

Mês  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)     Teste
0  Jan          323   225.184604        51   97.815396  72734.63
1  Fev          172    93.527751        65   78.472249  16086.77
2  Mar          216   144.838022        40   71.161978  31285.01
3  Abr          144    78.924823        42   65.075177  11365.17
4  Mai          358   120.013664        51  237.986336  42964.89

In [ ]:
#Pandas
#dados['Margem (%)'] = ((dados['Lucro (R$)']/dados['Vendas (R$)'])*100).round(1)

#Numpy
dados['Margem (%)'] = np.round((dados['Lucro (R$)']/dados['Vendas (R$)'])*100, 1)



display(dados)





Mês  Vendas (R$)  Custos (R$)  Clientes  Lucro (R$)  Margem (%)
0  Jan          323   225.184604        51   97.815396        30.3
1  Fev          172    93.527751        65   78.472249        45.6
2  Mar          216   144.838022        40   71.161978        32.9
3  Abr          144    78.924823        42   65.075177        45.2
4  Mai          358   120.013664        51  237.986336        66.5